apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-server
  labels:
    app: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: http
      name: http
    - port: {{ .Values.service.grpcPort }}
      targetPort: grpc
      name: grpc
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      name: metrics
  selector:
    app: {{ .Release.Name }}
    component: server
